require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/Documentation:
    Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'app/schemas/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/*.rb'